FROM python:3.10

WORKDIR /srv

COPY api.py ./

ARG BRANCH
COPY requirements-api-${BRANCH}.txt ./
RUN pip install -r requirements-api-${BRANCH}.txt

CMD ["sanic", "api.app", "--host=0.0.0.0", "--port=8000", "--workers=4", "--no-access-logs"]
