services:
  jschon-api:
    container_name: jschon-api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  jschon-ui:
    container_name: jschon-ui
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JSCHON_API=http://jschon-api:4444
      - JSCHON_FORWARDED_SECRET
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
